ecc/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from seasons import views

urlpatterns = [
    url(r'^$', views.Index),
    url(r'^contacts/', include('contacts.urls')),
    url(r'^games/', include('games.urls')),        
    url(r'^news/', include('news.urls')),    
    url(r'^season/', include('seasons.urls')),
    url(r'^links/', include('chesslinks.urls')),    
    url(r'^admin/', admin.site.urls),
]

seasons/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [

    
    url(r'^$', views.Index, name='seasons'),
    url(r'^index/$', views.Index, name='seasons'),
    url(r'^FixtureList/$', views.FixtureList, name='seasons'),
    url(r'^Next5Fixtures/$', views.Next5Fixtures, name='seasons'),
    url(r'^about/$', views.about, name='seasons'),
    url(r'^puzzles/$', views.puzzles, name='puzzles'),
    url(r'^last5results/$', views.Last5Results, name='seasons'),
    url(r'^matchresult/(?P<pFixture>\d+/$)', views.MatchResult, name='seasons'),]

seasons/models.py
from django.db import models

# Create your models here.
MATCH_RESULT_CHOICES = (
        ('W', 'Won'),
        ('L', 'Lost'),
        ('D', 'Draw'),
    )
    
BOARD_CHOICES = (
        ('O', 'Odd'),
        ('E', 'Even'),
        ('U', 'Unknown'),
    )
TEAM_CHOICES = (
        ('A', 'A'),
        ('B', 'B'),
        ('C', 'C'),
        ('D', 'D'),
        ('E', 'E'),
        ('F', 'F'),
        ('G', 'G'),
    )

VENUE_CHOICES = (
        ('H', 'Home'),
        ('A', 'Away'),
    )
BOARD_RESULT_CHOICES = (
        (2, '1-0'),
        (0, '0.5-0.5'),
        (1, '0-1'),
        (-1, 'Adjourned'),
        (-2, 'Adjudicated'),
    )

class Season(models.Model):
    name = models.CharField(max_length=5)
    fullname = models.CharField(max_length=9) 
    
    def __str__(self):
        return self.name

    class Admin:
        pass

class Player(models.Model):
    first_name = models.CharField(max_length=25)
    last_name = models.CharField(max_length=35)
    initials = models.CharField(max_length=5)
    ECF_reg = models.CharField(max_length=10,null=True)
    active = models.PositiveSmallIntegerField(null=True, blank=True)
    gradelist = models.ManyToManyField(Season, through='Grade')
    
    class Meta:
        ordering = ('last_name', 'first_name')
	
    def __str__(self):
        return '%s, %s' % (self.last_name,self.first_name)

    class Admin:
        pass

class League(models.Model):
    name = models.CharField(max_length=50)
    code = models.CharField(max_length=3)

    def __str__(self):
        return self.name

    class Admin:
        pass

class Team(models.Model):
    league = models.ForeignKey(League)
    name = models.CharField(max_length=20)
    number = models.PositiveSmallIntegerField(null=False, blank=False)
    letter = models.CharField(max_length=1)
    code = models.CharField(max_length=20)
    
    def __str__(self):
        return '%s League: %s %s' % (self.league.name,self.name, self.letter)


    class Admin:
        pass

class Boardresult(models.Model):
    homedisplay = models.CharField(max_length=10)
    awaydisplay = models.CharField(max_length=10)
    def __str__(self):
        return '%s' % (self.homedisplay)

    class Admin:
        pass

class MatchType(models.Model):
    matchtype_code = models.CharField(max_length=6)
    matchtype_name = models.CharField(max_length=20)
    
    def __str__(self):
        return '%s' % (self.matchtype_name)

    class Admin:
        pass

class Campaign(models.Model):
    season = models.ForeignKey(Season)
    team = models.ForeignKey(Team)
    captain = models.ForeignKey(Player)
    boards = models.PositiveSmallIntegerField(null=False, blank=False)
    division = models.PositiveSmallIntegerField(null=False, blank=False)

    def __str__(self):
        return '%s: %s - %s %s' % (self.season.name,self.team.league.name,self.team.name, self.team.letter)

    class Admin:
        pass

class Grade(models.Model):
    season = models.ForeignKey(Season)
    player = models.ForeignKey(Player)
    grade = models.PositiveIntegerField(null=True, blank=True)

    def __str__(self):
        return '%s: %s ' %(self.season, self.grade)

    class Admin:
        pass


                		
class Fixture(models.Model):
    campaign = models.ForeignKey(Campaign)
    opponent_club = models.CharField(max_length=50)
    opponent_team = models.CharField(max_length=1)
    matchtype = models.ForeignKey(MatchType)
    venue = models.CharField(max_length=1, choices=VENUE_CHOICES)
    date = models.DateTimeField()
    match_result = models.CharField(max_length=1,null=True, blank=True)
    our_score= models.DecimalField(null=True, blank=True, max_digits=2, decimal_places=1)
    their_score = models.DecimalField(null=True, blank=True, max_digits=2, decimal_places=1)
    white_on  = models.CharField(max_length=1, choices=BOARD_CHOICES,null=True, blank=True)
    captains_headline = models.TextField()
    captains_comment = models.TextField()
    #captains_headline = tinymce_models.HTMLField(null=True, blank=True)
    #captains_comment = tinymce_models.HTMLField(null=True, blank=True)

    def __str__(self):
        #return '%s: %s - %s %s' % (self.Campaign,self.date,self.opponent_club, self.opponent_team)
        return "%s %s: %s%s: %s '%s' (%s)" %(self.campaign.season.name,self.date,self.campaign.team.league.code,self.campaign.team.number,self.opponent_club, self.opponent_team, self.venue)

    class Meta:
        ordering = ['date']

    class Admin:
        pass

class Result(models.Model):
    fixture = models.ForeignKey(Fixture)
    board = models.PositiveSmallIntegerField(null=False, blank=False)
    our_player = models.ForeignKey(Player)
    boardresult = models.ForeignKey(Boardresult)
    opponent_name = models.CharField(max_length=30)
    opponent_grade = models.PositiveIntegerField(null=True, blank=True)

    def __str__(self):
        return "%s: %s%s: %s '%s' (%s) Board %s" %(self.fixture.campaign.season.name,self.fixture.campaign.team.league.code,self.fixture.campaign.team.number,self.fixture.opponent_club, self.fixture.opponent_team, self.fixture.venue,self.board)
        

    class Admin:
        pass

seasons/forms.py
from django import  forms
from django.db import models
from .models import *

TEAM_CHOICES = (
    ('*', 'All Teams'),
    ('TVL1', 'TVL1'),
    ('TVL2', 'TVL2'),
    ('TVL3', 'TVL3'),
    ('TVL4', 'TVL4'),
    ('MDX1', 'MDX1'),
    ('MDX2', 'MDX2'),
    ('HIL1', 'HIL1'),
    ('HIL2', 'HIL2'),
    ('HIL3', 'HIL3'),
    ('HIL4', 'HIL4'),
    ('TVJ1', 'TVJ1'),
    ('TVJ2', 'TVJ2'),
    ('TVJ3', 'TVJ3'),
)

TEAM_CHOICES2 = (
    ('*', 'All Teams'),
    ('1', 'TVL1'),
    ('2', 'TVL2'),
    ('3', 'TVL3'),
    ('4', 'TVL4'),    
    ('5', 'MDX1'),
    ('6', 'MDX2'),
    ('7', 'HIL1'),
    ('8', 'HIL2'),
    ('9', 'HIL3'),    
    ('10', 'HIL4'),

)
SEASONS_CHOICES = (
    ('16/17', '16/17'),
    ('15/16', '15/16'),
    ('14/15', '14/15'),
    ('13/14', '13/14'),
    ('12/13', '12/13'),
    ('11/12', '11/12'),
    ('10/11', '10/11'),
    ('09/10', '09/10'),
    ('08/09', '08/09'),
    ('07/08', '07/08'),
    ('06/07', '06/07'),
    ('05/06', '05/06'),
    ('04/05', '04/05'),
    ('03/04', '03/04'),
    ('02/03', '02/03'),
    ('01/02', '01/02'),
    ('00/01', '00/01'),
    ('99/00', '99/00'),
    ('98/99', '98/99'),
    ('97/98', '97/98'),
    ('96/97', '96/97'),
    ('95/96', '95/96'),
    ('94/95', '94/95'),
    ('93/94', '93/94'),
    ('92/93', '92/93'),
    ('91/92', '91/92'),
    ('90/91', '90/91'),   
    
)

class FixtureForm(forms.Form):
    team = forms.ChoiceField(choices=TEAM_CHOICES)
    season = forms.ChoiceField(choices=SEASONS_CHOICES)

class Contact2Form(forms.Form):
    team = forms.ChoiceField(choices=TEAM_CHOICES2)
    season = forms.ChoiceField(choices=SEASONS_CHOICES)
    opponent_team = forms.ModelChoiceField(Team.objects.all())

seasons/views.py
from django.http import HttpResponse
from django.template import loader
from django.shortcuts import render
from datetime import datetime

from .models import *
from .forms import FixtureForm

#def fixturelist(request):
#    if request.method == 'POST':
#        team_str = request.POST['team']
#        if team_str == "*":
#            fixture_list = Fixture.objects.filter(campaign__season__name =request.POST['season']).order_by('date')
#        else:
#            fixture_list = Fixture.objects.filter(campaign__team__code =request.POST['team'], campaign__season__name =request.POST['season']).order_by('date')
#        form = FixtureForm(request.POST)
#    else:
#        form = FixtureForm()
#        fixture_list = Fixture.objects.filter(campaign__season__name ='16/17').order_by('date')
#   return render_to_response('seasons/fixturelist.html', {'fixture_list': fixture_list,'form': form})

def Last5Results(request,):
    fixture_list = Fixture.objects.filter(date__lte = datetime.now() , our_score__gte=0).order_by('-date')[:5]
    template = loader.get_template('last5results.html')
    context = {'fixture_list': fixture_list,}
    return HttpResponse(template.render(context, request))

def Next5Fixtures(request):
    fixture_list = Fixture.objects.filter(date__gte = datetime.now() ).order_by('date')[:5]
    template = loader.get_template('Next5Fixtures.html')
    context = {'fixture_list': fixture_list,}
    return HttpResponse(template.render(context, request))

def MatchResult(request,pFixture):
    vTitle = "Welcome to Ealing Chess CLub"
    iFixture = int(pFixture.replace('/',''))
    fixture = Fixture.objects.get(id = iFixture)
    result_list = Result.objects.filter(fixture__id = iFixture).order_by('board')

    template = loader.get_template('matchresult.html')
    context = {'result_list': result_list, 'fixture': fixture,}
    return HttpResponse(template.render(context, request))

def about(request,):
    context = {'Welcome to Ealing Chess CLub':'Title',}
    template = loader.get_template('about.html')        
    return HttpResponse(template.render(context, request))

def Index(request,):
    vTitle = "Welcome to Ealing Chess CLub"
    template = loader.get_template('home.html')
    context = {'Welcome to Ealing Chess CLub':'Title',}            
    return HttpResponse(template.render(context, request))

def puzzles(request,):
    vTitle = "Welcome to Ealing Chess CLub"
    template = loader.get_template('puzzles.html')
    context = {'Welcome to Ealing Chess CLub':'Title',}            
    return HttpResponse(template.render(context, request))

def FixtureList(request):
    if request.method == 'POST':
        team_str = request.POST['team']
        if team_str == "*":
            fixture_list = Fixture.objects.filter(campaign__season__name =request.POST['season']).order_by('date')
        else:
            fixture_list = Fixture.objects.filter(campaign__team__code =request.POST['team'], campaign__season__name =request.POST['season']).order_by('date')
        form = FixtureForm(request.POST)
    else:
        form = FixtureForm()
        fixture_list = Fixture.objects.filter(campaign__season__name ='16/17').order_by('date')
    return render(request, 'fixturelist.html', {'fixture_list': fixture_list,'form': form})

seasons/templates/Next5Fixtures.html
{% block content %}
<body>


<p>
<table border =1>
<tr><td><b>Team</b></td><td><b>Date</b></td><td><b>Time</b></td><td><b>Opponent</b></td><td><b>Venue</b></td></tr>
{% for fixture in fixture_list %}
	<tr><td>{{ fixture.campaign.team.league.code}}{{ fixture.campaign.team.number}}</td><td>{{ fixture.date|date:"D d M"}}</td><td>{{ fixture.date|time:"H:i"}}</td><td>{{ fixture.opponent_club}}  '{{fixture.opponent_team }}'</td><td>({{fixture.venue }})</td></tr> 
{% endfor %}

</table>
</body>
{% endblock %}

seasons/templates/about.html
{% extends "base.html" %}
{% block content %}<hr>


 
	<h1>About the club:</h1>

	Ealing is always looking for new members and offers a warm welcome to chess players of all strengths, nationalities and ages.  
	Whether you are a keen amateur or a budding GM we want to hear from you.  For seasoned players we can offer the opportunity of competitive chess in one of our seven league teams.  
	Alternatively, if you just want to enjoy a game of social chess, there are always members happy to oblige with a game.  
	Although we are not a club for complete beginners, we can promise that your chess will improve with regular practice against our stronger players.
	<p>
	We are fortunate in having a comfortable and relatively tranquil venue in a function room above the Harvester Restaurant and Pub at the corner of Boston Manor Road and Haslemere Avenue W7.  
	Here you can play an enjoyable game with an accompanying drink, or follow your game with a meal from the restauraunt below.
	<p></p>
	We meet on Mondays from 7.30 pm throughout the year, save for Christmas and New Year.
	<p>The club currently runs five teams in the local chess leagues, which run from September to May each year, providing competitive playing opportunities for players of all abilities.  
	Our first teams (both in Division One of their respective leagues) involve contests with some of the strongest players in the area, with top boards typically BCF 175+.  
	Conversely, the Hillingdon League offers a "nursery slope" for the aspiring player.   


	<pre>
	<b>League           Captain              Div     Team	  Strength</b>
	Thames Valley    Mike Lamb            One     1st Team	  BCF 150+
	                 Alastair Jonstone    Two     2nd Team	  BCF 100-150
	                 Geoff Richards       Three   3rd Team    BCF <110
	Middlesex        David Ebbett         One     1st Team	  BCF 150+
	                 Chris Greenshields   Two     2nd Team	  BCF 100-150
	Hillingdon       Pierre Davies        Three   1st Team    BCF <100
	                 David Reichenberg    Three   2nd Team    BCF <100 
	</pre>

	<p>
	During the summer months, the club runs a number of in-house competitions, such as the Summer Handicap Tournament (with playing time determined by grade) and an Annual Lightning Championship.  
	In addition, the Club Championship is played for a prestigious trophy that has been awarded every year since 1903!
	From time to time, the club also hosts special events, such as simultaneous displays or instructional talks from strong players.  
	A few years ago we even played host to a visiting team from Mongolia! 
	We have an excellent Club magazine in which we publish members games and reviews of all the teams performances and results.  
	Members on our e-mail list also receive regular newsletters to keep them informed and entertained.

	<h2>Player Grading</h2>
	All league games are submitted to the ECF (English Chess Federation) for grading.  Dont worry if you dont have a grade when you first join Ð our stronger members will soon form a view of your playing strength and estimate your grade.
	<h2>Club History</h2>
	Ealing has a proud tradition as one of the oldest chess clubs in the country.  Founded in 1885 we have met ever since, including during the two world wars!  It has a long and fascinating history.  If you would like to learn more, follow the link. 
	<h2>Are you interested?</h2> 
	If you are interested in joining the club please either contact the Secretary, 
	<br>David Ebbett - Telephone 0208 997 7872  - Email davidebbett@yahoo.co.uk <br><br>
	Alternatively turn up at the Club any Thursday.  Come along, without obligation and to see if Ealing is the chess club for you.  
	After three visits, if you decide to join, the membership fee becomes due.  The annual subscription is £40 (unwaged £20) due in June each year.

	    </p>

{% endblock %}

seasons/templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
{% load static %}
<!-- this template was designed by http://www.tristarwebdesign.co.uk - please visit for more templates & information - thank you. -->

<head>

<title>Welcome to Ealing Chess Club Online!</title> <!-- change to whatever you want as the title for your website -->
<meta name="description" content=" " /> <!-- enter a description for your website inside the " " -->
<meta name="keywords" content=" " /> <!-- enter a string of keywords that relate to your website inside the " " -->
<meta http-equiv="Content-Language" content="en-gb" />
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252" />

<link rel="stylesheet" type="text/css" href="{% static "css/style.css" %}" />

</head>

<body>

<div id="topCont">
	<div id="top">
		<div id="topleft"></p></div>
		<div id="topright"><p><i>"Those who say they understand chess, understand nothing"
-- Robert HUBNER</i></p></div>
	</div>
	<div id="header">
		<div id="headerleft">
		<img alt="" src="{% static "images/chess.jpg" %}" <a title="skip to content" href="#mainCont"></a></div>
		<div id="headerright">
			<h1>Ealing Chess Club</h1>
			<h2>Est. 1885</h2>
		</div>
	</div>
</div>

<div id="mainCont">
	<div id="main">
		<div id="mainmenu">
			<ul>
				<li><a class="active" title="home" href="/">Home</a></li>
				<li><a title="link one" href="/season/about">About The Club</a></li>
				<li><a title="link two" href="/news">News</a>
					
					</li>
				<li><a title="link three" href="/events">Club Events</a></li>
				<li><a title="link four" href="/season/FixtureList">Fixtures + Results</a></li>
				<li><a title="link six" href="/links">Chess Links</a></li>
				<li><a title="link seven" href="/games">Games Viewer</a></li>
				<li><a title="link eight" href="/season/puzzles">Daily Puzzle</a></li>	
				<li><a title="link nine" href="/contacts">Club Contacts</a></li>				
                                <hr>
				<li><a title="link ten" href="http://www.facebook.com/ealingchess">Facebook Page</a></li>
                                <li><a title="link eleven" href="http://www.ealingjuniorchessclub.co.uk">Ealing Juniors Page</a></li>

			</ul><hr>

			<div id="fix">
			 load_tags  
			<p><h2>Last 5 Results</h2></p>
			<p>{last5results </p>
			<p><h2>Next 5 fixtures</h2></p>
				next5fixtures 
			</div>
			

		</div>
		<div id="maincontent">
{% block content %}{% endblock %}

		</div>
		<div class="bottom"></div>
	</div>
</div>

<div id="footerCont">
	<div id="footer">
		<div id="footerleft">
			<p><a title="back to top" href="#topCont">Back to Top ^</a></p>
		</div>
		<div id="footerright">
			<p>layout design by <a title="derby web design" href="http://www.tristarwebdesign.co.uk">tristar web design</a></p>
			<p>coding design by <a title="app design" href="http://www.venatio.co.uk">Venatio Ltd</a></p>		</div>
		<div class="bottom"></div>
	</div>
</div>

<!-- Google Analytics -->

<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("UA-16312075-1");
pageTracker._trackPageview();
} catch(err) {}</script>
</body>

</html>

seasons/templates/fixturelist.html
{% extends "base.html" %}
{% block content %}
<body>
	<h1> Fixtures</H1>
	<hr>
    <form action="." method="POST">
        {% csrf_token %}
		Show Fixtures for:  {{ form.as_table }} 
		<input type="submit" value="Go!">
    </form>
	<hr>

<p>
<table border =1>
<tr><td><b>Team</b></td><td><b>Date</b></td><td><b>Time</b></td><td><b>Opponent</b></td><td><b>Venue</b></td><td><b>Result</b></td></tr>
{% for fixture in fixture_list %}
	<tr><td>{{ fixture.campaign.team.league.code}}{{ fixture.campaign.team.number}}</td><td>{{ fixture.date|date:"D d M Y"}}</td><td>{{ fixture.date|time:"H:i"}}</td><td>{{ fixture.opponent_club}}  '{{fixture.opponent_team }}'</td><td>({{fixture.venue }})</td><td><a href=../matchresult/{{fixture.id}}>
	{% if fixture.match_result  %}	
	{{fixture.match_result }}:  {{fixture.our_score}}-{{fixture.their_score}}
	{% endif %}
	</td></tr> 
{% endfor %}

</table>
</body>
{% endblock %}

seasons/templates/home.html
{% extends "base.html" %}
{% block content %}
{% load static %}
	<h1>Welcome to Ealing Chess Club's Website</h1>
<hr>
	<p align="justify">We are a friendly &amp; social chess club who try and provide a friendly and competitive environment for chess lovers of all abilities. We are one of the longest established clubs in London, having met weekly since 1885.</p>
	<p align="center">
	<img src="{% static "home/chesspic_a.jpg" %}" width="195" height="140">
	<img src="{% static "home/chesspic_e.jpg" %}" width="195" height="140">
	<img src="{% static "home/chesspic_d.jpg" %}" width="195" height="140">
	</p>
	<p align="justify">Currently our club night is Monday evenings from 7:30pm. In the
	spacious Sports Bar of The Old Actonians Sports Club, Gunnersbury Drive (off Popes Lane), Ealing, London W5 4LL.</p>

	<p align="justify">The venue offers a friendly environment in which to play chess with a good range of beer and light refreshments available to enjoy during or after games. The club is well served by public transport being just an 8 minute walk from Acton Town Tube and on the route of the E3 bus. There is a small car park at the club, along with parking on the ajoining streets (after 7pm)<br> A Map can be found <a href="https://www.google.com/maps/@51.5021573,-0.2887742,18z" TARGET="_blank">here</a></p>
	<p align="justify">During the League season, Junior and some senior matches will take place on selected wednesdays at the former London Victoria Sports Ground in Boddington Gardens W3 9AP<br> A Map can be found <a href="https://goo.gl/maps/5lgSh" TARGET="_blank">here</a></p>
	<p align="justify">New Members (from Grandmaster to beginners!) are always welcome. Feel free to just pop down on a Monday, or even better, give the <a href="contacts">new members co-ordinator</a> a call or email first and we will do our best to ensure there will be a member of the same standard around to give you a good game or two!
	</p>
	{% load seasons_extras %}




		
		
<br>
Click <a title="news" href="/news">here</a> for older news 	
{% endblock %}
</div>

seasons/templates/last5results.html
{% block content %}
<body>


<p>
<table border =1>
<tr><td><b>Team</b></td><td><b>Date</b></td><td><b>Opponent</b></td><td><b>Venue</b></td><td><b>Result</b></td></tr>
{% for fixture in fixture_list %}
	<tr><td>{{ fixture.campaign.team.league.code}}{{ fixture.campaign.team.number}}</td><td>{{ fixture.date|date:"d M"}}</td><td>
		{{ fixture.opponent_club}}  '{{fixture.opponent_team }}'</td><td>({{fixture.venue }})</td>
		<td><a href=../matchresult/{{fixture.id}} >
	{% if fixture.match_result  %}	
	{{fixture.match_result }}:  {{fixture.our_score}}-{{fixture.their_score}}
	{% endif %} 
	</td></tr> 
{% endfor %}

</table>
</body>
{% endblock %}

seasons/templates/matchresult.html
{% extends "base.html" %}
{% block content %}
<h1>Match Result</H1>
<hr>
<table border =1>      
	<tr><td><b>Season</b></td>		<td>{{ fixture.campaign.season.name }}</td></tr>
	<tr><td><b>Date</b></td>		<td>{{ fixture.date|date:"D d M Y"}}</td></tr>
	<tr><td><b>Competition:</b></td><td>{{fixture.campaign.team.league.name}} League Division {{fixture.campaign.division}}</td></tr>
	<tr><td><b>Fixture<b></td>		<td>{% ifequal fixture.venue 'H' %}
    										{{fixture.campaign.team.name}} '{{ fixture.campaign.team.letter}}' v {{ fixture.opponent_club }} '{{ fixture.opponent_team }}'
										{% else %}
											{{ fixture.opponent_club }} '{{ fixture.opponent_team }}' v {{fixture.campaign.team.name}} '{{ fixture.campaign.team.letter}}' 
										{% endifequal %}</td></tr>
	<tr><td><b>Result</b></td>		<td>{{ fixture.match_result}}: {{ fixture.our_score|floatformat}}-{{ fixture.their_score|floatformat}}</td></tr>
</table>
<hr>

<h2>Scorecard</h2>
<br>
{% ifequal fixture.venue 'H' %}
	<table border =1>
	<tr><td><b>Board</b></td><td><b>Grade</b></td><td><b>{{fixture.campaign.team.name}} '{{ fixture.campaign.team.letter}}'</b></td><td><b><center>v</center></b></td><td><b>{{ fixture.opponent_club }} '{{ fixture.opponent_team }}'</b></td><td><b>Grade</b></th></tr>
	{% for result in result_list %}
		<tr><td>{{ result.board}}</td>
			<td>{{ result.our_player.gradelist.grade_set }}




			{% for gradep in result.our_player.gradelist.all %}

				

				{% endfor %}</td>






			<td>{{ result.our_player.first_name }} {{ result.our_player.last_name }}</td>
			<td><center>{{ result.boardresult.homedisplay}}</center></td>
			<td>{{result.opponent_name }}</td>
			<td>{{result.opponent_grade }} </td></tr> 
	{% endfor %}
<tr><td><b>Total</b></td><td><b></b></td><td><b></b></td><td><b><center>{{fixture.our_score|floatformat}}-{{fixture.their_score|floatformat}}</center></b></td><td><b></b></td><td><b></b></th></tr>
	</table>
	

{% else %}
	<table border =1>
	<tr><td><b>Board</b></td><td><b>Grade</b></td><td><b>{{ fixture.opponent_club }} '{{ fixture.opponent_team }}'</b></td><td><b><center>v</center></b></td><td><b>{{fixture.campaign.team.name}} '{{ fixture.campaign.team.letter}}'</b></td><td><b>Grade</b></th></tr>
	{% for result in result_list %}
		<tr><td>{{ result.board}}</td><td>{{result.opponent_grade }}</td><td>{{result.opponent_name }}</td><td><center>{{ result.boardresult.awaydisplay}}</center></td><td>{{ result.our_player.first_name }} {{ result.our_player.last_name }}</td><td>
		
		{{ result.our_player.gradelist.grade.all }}
		
 </td></tr> 
{% endfor %}
<tr><td><b>Total</b></td><td><b></b></td><td><b></b></td><td><b><center>{{fixture.their_score|floatformat}}-{{fixture.our_score|floatformat}}</center></b></td><td><b></b></td><td><b></b></th></tr>
	</table>

{% endifequal %}
<br>
<h2>Captains Comment</h2>
{% autoescape off %}

<br>
{% if fixture.captains_comment  %}
	{{ fixture.captains_comment }}
{% endif %}
<br>
{% endautoescape %}

{% endblock %}

seasons/templates/puzzles.html
{% extends "base.html" %}
{% block content %}<hr>

<h1>Daily Puzzle:</H1>
 
	<iframe width="310" scrolling="no" height="341" frameborder="0" src="http://www.shredderchess.com/online/playshredder/
	gdailytactics.php?mylang=en&mysize=32"></iframe>

{% endblock %}